
import React from 'react';

const Disclaimer: React.FC = () => {
  return (
    <footer className="w-full bg-dark-base-200 border-t border-dark-base-300 mt-8">
        <div className="container mx-auto px-4 py-4 text-center text-xs text-gray-500">
            <p className="font-bold">Disclaimer</p>
            <p>
                The analysis provided by this tool is generated by an AI model and is for informational purposes only. It should not be considered financial advice. Trading involves substantial risk, and you should always conduct your own research and consult with a qualified financial advisor before making any investment decisions.
            </p>
        </div>
    </footer>
  );
};

export default Disclaimer;
